CREATE TABLE livro(
id_livro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(254),
autor VARCHAR(254),
ano_publicacao INTEGER
)

INSERT INTO LIVRO(nome,autor,ano_publicacao)
VALUES ('Quarto de Despejo','Carolina Maria de Jesus', '2000');
INSERT INTO LIVRO(nome,autor,ano_publicacao)
VALUES ('Todas as suas imperfeições','Collen Hoover', '2023');
INSERT INTO LIVRO(nome,autor,ano_publicacao)
VALUES ('Turma da Mônica','Mauricio de Souza', '2019');

SELECT l.NOME, l.AUTOR, l.ANO_PUBLICACAO 
FROM LIVRO l 

SELECT 1
FROM LIVRO l 
WHERE nome = ?